require("plugins-install")

require("core.settings")
require("core.keybindings")
require("core.theme")

require("plugins.lsp.keybindings")
require("plugins.lsp.rust")
require("plugins.lsp.ts")
require("plugins.lsp.cs")
require("plugins.lsp.python")
require("plugins.lsp.gleam")
require("plugins.lsp.nix")
require("plugins.lsp.typst")
require("plugins.lsp.go")
require("plugins.lsp.null")

require("plugins.bufferline")
require("plugins.completion")
require("plugins.comment")
require("plugins.coq")
require("plugins.dap")
require("plugins.diffview")
require("plugins.flash")
require("plugins.lazydocker")
require("plugins.lualine")
require("plugins.neotest")
require("plugins.neogit")
require("plugins.oil")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")
