require("plugins-install")

require("core.settings")
require("core.keybindings")
require("core.theme")

require("plugins.bufferline")
require("plugins.completion")
require("plugins.comment")
require("plugins.dap")
require("plugins.diffview")
require("plugins.flash")
require("plugins.gitui")
require("plugins.lualine")
require("plugins.oil")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")

require("plugins.lsp.keybindings")
require("plugins.lsp.rust")
require("plugins.lsp.ts")
require("plugins.lsp.cs")
require("plugins.lsp.python")
